import january from "@/assets/ai-assistant.jpg";
import tiger from "@/assets/tiger-vision.jpg";
import robotics from "@/assets/robotics.jpg";
import iot from "@/assets/industrial-iot.jpg";

export const imagery = { january, tiger, robotics, iot };

export const projects = [
  { name: "JANUARY", type: "Personal project", year: "2026", category: "AI / ENGINEERING", image: january, description: "A multimodal AI engineering assistant bringing conversation, voice, vision, file processing, coding and desktop automation into one system. Dynamic routing across Gemini, OpenAI, Claude and Ollama models supports multilingual workflows in more than 100 languages.", details: "React · Node.js · SQLite · Multimodal AI" },
  { name: "Nova", type: "Freelance project", year: "2026", category: "VOICE AI", image: january, description: "An AI calling agent for Indira Pachhi’s Pickles and Chutney Powders, automating voice conversations and customer communication while keeping interaction records for the business.", details: "Gemini API · PostgreSQL · Voice interaction" },
  { name: "Tiger Re-Identification", type: "Research internship · IIIT Dharwad", year: "2026", category: "COMPUTER VISION", image: tiger, description: "Research into identifying Amur tigers from stripe patterns. Compared CNNs and transformers with metric-learning losses, analyzed embeddings and explored SHAP and LIME for explainability.", details: "AlexNet · ResNet-18 · EfficientNet-B0 · ViT · Swin" },
  { name: "EduForge", type: "Industry project · HAEGL Technologies", year: "2026", category: "EDTECH / AI", image: january, description: "An AI-assisted question paper and academic authoring platform for NLE’s Mahesh PU College, supporting JEE and NEET preparation with question evaluation and solution generation.", details: "React · Vite · Node.js · Gemini" },
  { name: "Optimized UGV Drivetrain", type: "Institutional research", year: "2025", category: "ROBOTICS", image: robotics, description: "Designed, sized and validated a propulsion system for a lab-scale unmanned ground vehicle. Tested under a 55 kg payload, achieving approximately 80% of defined performance requirements and producing three research papers.", details: "Motor selection · Mechanical design · Validation" },
  { name: "Water Treatment Mini Plant", type: "Senior design project", year: "2025", category: "IOT / AUTOMATION", image: iot, description: "An IoT-enabled water treatment plant monitoring pH and temperature in real time, automatically dosing acidic or basic solutions to move samples toward neutral pH. Testing achieved approximately 88% success.", details: "IoT · Circuit.io · MATLAB Simulink" },
  { name: "CNN Object Tracking", type: "Machine learning course project", year: "2023", category: "ROBOTICS / VISION", image: robotics, description: "A simulated robot with a camera tracked a moving object in Webots using a trained CNN, reaching approximately 80% tracking accuracy.", details: "Webots · CNN · Robotic navigation" },
  { name: "YOLOv8 Factory Inspection", type: "CVDIP course project", year: "2024", category: "COMPUTER VISION", image: robotics, description: "A simulated DJI Mavic drone inspected a virtual factory using YOLOv8 to detect workers, machinery and vehicles in real time, reaching approximately 87% detection accuracy.", details: "Webots · YOLOv8 · Drone simulation" },
  { name: "Object Detection & Classification", type: "CVDIP course project", year: "2024", category: "COMPUTER VISION", image: tiger, description: "Built an image detection and classification workflow in Google Colab using labeled datasets, pretrained CNNs, transfer learning, augmentation and fine-tuning.", details: "Google Colab · CNN · Transfer learning" },
  { name: "Automatic Pet Feeder", type: "Mini project", year: "2024", category: "EMBEDDED SYSTEMS", image: iot, description: "An automated food and water dispenser with scheduled quantities, a mobile control app and remaining-level information. The prototype achieved approximately 76% success in testing.", details: "SolidWorks · Circuit.io · MIT App Inventor" },
  { name: "Voice Recognition Robot", type: "Minor project", year: "2024", category: "ROBOTICS / VOICE", image: robotics, description: "A voice-controlled two-wheel robot prototyped in Webots and built around a Raspberry Pi Pico, with a mobile app for commands. It achieved approximately 92% success in command recognition and execution.", details: "Python · Webots · Raspberry Pi Pico" },
  { name: "Hybrid Solar Dryer Dashboard", type: "Industry project · HAEGL Technologies", year: "2026", category: "IOT / WEB", image: iot, description: "A web monitoring dashboard and embedded IoT system that collects and presents operating data from an industrial hybrid solar dryer.", details: "React · Vite · Node.js · Embedded IoT" },
  { name: "InQuote", type: "Industry project · HAEGL / ESSAR Labs", year: "2026", category: "SOFTWARE", image: january, description: "A quotation and invoice platform with Tally-oriented workflows, plus an Electron desktop edition with SQLite for offline operation.", details: "React · Node.js · PostgreSQL · Electron · SQLite" },
  { name: "NLE’s Rotary School Website", type: "Industry project · HAEGL Technologies", year: "2026", category: "WEB DEVELOPMENT", image: january, description: "A responsive, dynamic and content-editable website for NLE’s Rotary School, Hubballi, built for its CBSE-oriented information needs.", details: "React · Vite · Node.js · PostgreSQL" },
  { name: "Smart Medical Kit", type: "Industry project · HAEGL Technologies", year: "2026", category: "HEALTH / IOT", image: iot, description: "An embedded sensing system combining a 20×20 pressure matrix and a gyroscopic wrist-motion device to visualize pressure distribution, center of pressure and movement for clinical assessment.", details: "Embedded systems · Sensors · Data visualization" },
  { name: "STARK-VISION", type: "Personal project", year: "2026", category: "PRIVACY / VISION", image: tiger, description: "A privacy-first facial recognition PWA that processes faces locally in the browser, supporting multiple-face recognition, age and gender estimates, offline operation and local descriptor storage.", details: "Next.js · TypeScript · face-api.js · SQLite" },
  { name: "Vision-Based Robot Simulator", type: "Personal project", year: "2026", category: "ROBOTICS / 3D", image: robotics, description: "A web robotics lab simulating about 20 systems. Webcam-based pose and hand landmarks are mapped through motion filtering and kinematics to a real-time 6-DOF robotic arm.", details: "React · Three.js · React Three Fiber · MediaPipe" },
  { name: "HAEGL PARAKRAMA Deployment", type: "HAEGL Technologies", year: "2026", category: "DEPLOYMENT", image: january, description: "Production deployment of the HAEGL PARAKRAMA website, including cPanel hosting configuration, publishing and live accessibility validation.", details: "cPanel · Production hosting" },
  { name: "Terra CRM Testing", type: "HAEGL Technologies", year: "2026", category: "QUALITY ASSURANCE", image: january, description: "Functional testing and quality assurance across CRM workflows: validating features, identifying defects and regression-testing corrections.", details: "Functional testing · Regression testing" },
  { name: "Multi-Application Deployment", type: "HAEGL Technologies", year: "2026", category: "DEPLOYMENT", image: iot, description: "Deployed and validated InQuote, EduForge, the Hybrid Solar Dryer Dashboard and Smart Medical Kit web application for production access and client demonstrations.", details: "cPanel · Full-stack deployment" },
];