import image0 from "@/assets/january.jpg";
import image1 from "@/assets/nova.jpg";
import image2 from "@/assets/tiger-reid.jpg";
import image3 from "@/assets/eduforge.jpg";
import image4 from "@/assets/ugv-drivetrain.jpg";
import image5 from "@/assets/water-treatment.jpg";
import image6 from "@/assets/cnn-tracking.jpg";
import image7 from "@/assets/yolo-factory.jpg";
import image8 from "@/assets/object-classification.jpg";
import image9 from "@/assets/pet-feeder.jpg";
import image10 from "@/assets/voice-robot.jpg";
import image11 from "@/assets/solar-dryer.jpg";
import image12 from "@/assets/inquote.jpg";
import image13 from "@/assets/rotary-school.jpg";
import image14 from "@/assets/medical-kit.jpg";
import image15 from "@/assets/stark-vision.jpg";
import image16 from "@/assets/robot-simulator.jpg";
import image17 from "@/assets/parakrama.jpg";
import image18 from "@/assets/terra-crm.jpg";
import image19 from "@/assets/multi-deployment.jpg";

export const imagery = { january: image0, tiger: image2, robotics: image4, iot: image5 };

export const projects = [
  { name: "JANUARY", type: "Personal project", year: "2026", category: "AI / ENGINEERING", image: image0, description: "JANUARY is a multimodal AI engineering assistant designed to combine conversational AI, voice interaction, computer vision, file processing, coding assistance, and desktop automation into a single intelligent system. The system integrates multiple AI models including Google Gemini, OpenAI, Anthropic Claude, and Ollama-based models through a dynamic model-routing and fallback architecture, allowing the assistant to switch between models based on availability, quota limitations, and task requirements. JANUARY supports voice and text interaction, uses the system camera for visual understanding, processes user-provided files, assists with programming, and can generate websites and software through natural-language instructions. The application is built using React, Node.js, and SQLite, with a strong emphasis on multimodal interaction and local desktop integration. The system is designed to support more than 100 languages, including more than 20 Indian languages, making it suitable for multilingual voice-driven engineering and productivity workflows.", details: "React · Node.js · SQLite · Multimodal AI" },
  { name: "Nova", type: "Freelance project", year: "2026", category: "VOICE AI", image: image1, description: "Nova is an AI-powered calling agent developed for Indira Pachhi’s Pickles and Chutney Powders to automate customer communication and support customer relationship management for a small-scale business. The system uses the Gemini API as its conversational intelligence layer and is designed to conduct automated voice interactions, understand customer requests, generate appropriate responses, and manage customer communication workflows. The project combines conversational AI with backend database infrastructure to maintain customer information and interaction records. PostgreSQL and Supabase were used for persistent data storage and backend integration. The project provided practical experience in developing AI voice agents, integrating generative AI models into business workflows, and designing AI-driven customer relationship management systems.", details: "Gemini API · PostgreSQL · Voice interaction" },
  { name: "Tiger Re-Identification", type: "Research internship · IIIT Dharwad", year: "2026", category: "COMPUTER VISION", image: image2, description: "This research project focused on the re-identification of Amur tigers using their unique stripe patterns as visual identification features. The objective was to investigate deep learning and metric-learning techniques capable of learning discriminative representations that can distinguish individual tigers across different images and viewing conditions. Five different deep learning architectures—AlexNet, ResNet-18, EfficientNet-B0, GoogLeNet, and Vision Transformer (ViT)—were trained and evaluated using multiple loss functions, including Triplet, Triplet-Hard, Contrastive, and Cross-Entropy losses. A Swin Transformer model was also investigated with the same loss-function approaches to study Transformer-based feature representations for animal re-identification. The project involved embedding visualization and feature-space analysis to understand how different models separated individual identities. Explainable AI techniques such as SHAP and LIME were explored to understand model predictions and feature importance. Re-identification performance was analyzed using standard evaluation metrics including mean Average Precision (mAP), Top-1 accuracy, and Top-5 accuracy. The project provided hands-on research experience in deep learning, metric learning, computer vision, Transformer architectures, explainable AI, embedding analysis, and Re-ID evaluation.", details: "AlexNet · ResNet-18 · EfficientNet-B0 · ViT · Swin" },
  { name: "EduForge", type: "Industry project · HAEGL Technologies", year: "2026", category: "EDTECH / AI", image: image3, description: "EduForge is a smart question-paper generation and academic authoring platform developed for NLE’s Mahesh PU College to support students preparing for competitive examinations such as JEE and NEET. The application was developed as a full-stack web platform using React, Vite, and Node.js, with a user-friendly interface for creating and managing examination content. Gemini was integrated into the platform to provide AI-assisted question evaluation, intelligent solution generation, and automated academic assistance. The system combines structured question-paper creation with generative AI capabilities to simplify the preparation and evaluation of examination material. The project provided practical experience in integrating large language models into an educational workflow and developing a production-oriented full-stack application around AI-assisted academic functionality.", details: "React · Vite · Node.js · Gemini" },
  { name: "Optimized UGV Drivetrain", type: "Institutional research", year: "2025", category: "ROBOTICS", image: image4, description: "This institutional research project focused on the modelling, sizing, development, and validation of an optimized propulsion system and drivetrain for a laboratory-scale Unmanned Ground Vehicle. The project began with calculations for the required torque, speed, and acceleration based on the expected operating conditions and payload requirements of the UGV. A systematic comparison was then carried out between Geared BLDC motors and Hub motors to determine the motor configuration most suitable for the vehicle. Based on the selected propulsion system, motor mounts were designed and integrated into the UGV chassis, followed by motor calibration and system-level testing. The completed vehicle was tested under a 55 kg payload to evaluate torque, speed, and acceleration performance and validate the design calculations. The project achieved approximately 80% success against the defined performance requirements and resulted in three research papers documenting the methodology, analysis, and findings.", details: "Motor selection · Mechanical design · Validation" },
  { name: "Water Treatment Mini Plant", type: "Senior design project", year: "2025", category: "IOT / AUTOMATION", image: image5, description: "This project involved the design and development of an IoT-based water treatment mini plant capable of monitoring water quality parameters and automatically controlling the treatment process. The system measures pH, temperature, and water-quality parameters in real time and uses automated control logic to maintain the required water condition. When the water becomes acidic, the system activates a base-dosing mechanism, while basic water triggers the addition of an acidic solution to move the sample toward a neutral pH. Circuit.io was used for circuit-level simulation, while MATLAB Simulink was used to model the overall system architecture and control behaviour. An IoT dashboard was developed to display the monitored parameters and provide real-time visibility into the treatment process. The developed system achieved approximately 88% success during testing, and the project resulted in one research paper.", details: "IoT · Circuit.io · MATLAB Simulink" },
  { name: "CNN Object Tracking", type: "Machine learning course project", year: "2023", category: "ROBOTICS / VISION", image: image6, description: "This project explored the application of Convolutional Neural Networks for object tracking in a simulated robotic environment. A virtual world was first created using Webots, after which a camera was mounted on the simulated robot to provide visual information about the environment. A simple object was created and programmed to navigate along a predefined track, generating visual and trajectory information for the learning system. A CNN model was then trained to learn the object’s movement and track its path within the simulated environment. The resulting system achieved approximately 80% tracking accuracy. The project demonstrated how vision-based machine learning could be applied to robotic navigation and provided a foundation for potential future applications in autonomous vehicle perception and self-driving vehicle prototyping.", details: "Webots · CNN · Robotic navigation" },
  { name: "YOLOv8 Factory Inspection", type: "CVDIP course project", year: "2024", category: "COMPUTER VISION", image: image7, description: "This project investigated the use of YOLOv8 for automated visual inspection within a simulated industrial environment. A factory-like world was developed using Webots, and a DJI Mavic drone model equipped with a camera was introduced into the simulation. The drone was programmed to navigate throughout different areas of the virtual factory while continuously capturing visual information. YOLOv8 was integrated into the control and inspection pipeline to perform real-time object detection. The system was capable of identifying workers, industrial equipment, machines, and vehicles used for transportation within the factory environment. The model achieved approximately 87% detection accuracy and demonstrated how drone-based computer vision could be used for automated factory inspection, monitoring, and industrial automation applications.", details: "Webots · YOLOv8 · Drone simulation" },
  { name: "Object Detection & Classification", type: "CVDIP course project", year: "2024", category: "COMPUTER VISION", image: image8, description: "This project focused on developing an object detection and classification workflow using Google Colab as the model development and training environment. Labeled image datasets were prepared for training and testing, with different object categories represented within the dataset. A computer vision pipeline was developed to process the images and perform object detection and classification based on object type. Transfer learning techniques using pretrained CNN architectures were explored to improve feature extraction and reduce the training requirements of the model. Dataset augmentation and model fine-tuning were used to improve classification performance and generalization. The project provided practical experience in dataset preparation, CNN-based feature extraction, transfer learning, model training, and computer vision evaluation using Google Colab.", details: "Google Colab · CNN · Transfer learning" },
  { name: "Automatic Pet Feeder", type: "Mini project", year: "2024", category: "EMBEDDED SYSTEMS", image: image9, description: "The Automatic Pet Feeder was developed as an automated system capable of dispensing predefined quantities of food and water to a pet at scheduled times. The mechanical structure of the feeder was designed using SolidWorks, while the electronic circuit and control concept were simulated using Circuit.io before physical implementation. A mobile application was developed using MIT App Inventor to allow users to configure feeding schedules and set the required quantity of food and water. The application also displayed the remaining quantities, providing the user with information about the current food and water levels. The system combined mechanical design, electronic control, mobile application development, and automation into a single prototype. Testing of the developed system resulted in approximately 76% success under the defined operating conditions.", details: "SolidWorks · Circuit.io · MIT App Inventor" },
  { name: "Voice Recognition Robot", type: "Minor project", year: "2024", category: "ROBOTICS / VOICE", image: image10, description: "This project involved the development of a two-wheel-drive robotic vehicle controlled through voice commands from a mobile application. The robot’s movement and control logic were initially developed and tested within Webots using Python to validate the behaviour of the system before physical implementation. Voice datasets were prepared and processed using Google Colab, where the different stages required for developing a voice-recognition system were implemented and trained. An MIT App Inventor application was subsequently developed to provide the user interface for sending voice-based commands to the robot. The application communicated with a Raspberry Pi Pico, which acted as the embedded controller for the physical robot. The completed system achieved approximately 92% success in recognizing and executing the required commands, demonstrating the integration of voice recognition, mobile applications, embedded systems, and robotics.", details: "Python · Webots · Raspberry Pi Pico" },
  { name: "Hybrid Solar Dryer Dashboard", type: "Industry project · HAEGL Technologies", year: "2026", category: "IOT / WEB", image: image11, description: "This project involved the development of a web-based monitoring dashboard and embedded IoT system for a hybrid solar dryer developed for an industrial client. The dashboard was developed using React and Vite for the frontend and Node.js for backend services. The software interface was designed to display important dryer parameters and provide a convenient way to monitor the operating condition of the system. In parallel with the software development, an embedded IoT system was developed and integrated with the physical solar dryer to collect and communicate operational data to the dashboard. The project combined embedded hardware, IoT communication, web development, and industrial monitoring into a single integrated system.", details: "React · Vite · Node.js · Embedded IoT" },
  { name: "InQuote", type: "Industry project · HAEGL / ESSAR Labs", year: "2026", category: "SOFTWARE", image: image12, description: "InQuote is a full-stack quotation and invoice generation platform developed for ESSAR Labs to simplify accounting-related workflows and provide a more accessible alternative for managing quotations and invoices. The web application was developed using React, Vite, and Node.js with PostgreSQL as the database. The system was designed with a user-friendly interface and included integration capabilities for Tally-based accounting workflows. To provide offline functionality, the web application was converted into a standalone desktop software application using Electron. SQLite 3 was used as the local database for the desktop version, allowing the software to operate without an active internet connection. The project provided experience in full-stack application development, database architecture, desktop application packaging, accounting software integration, and offline-first application design.", details: "React · Node.js · PostgreSQL · Electron · SQLite" },
  { name: "NLE’s Rotary School Website", type: "Industry project · HAEGL Technologies", year: "2026", category: "WEB DEVELOPMENT", image: image13, description: "This project involved developing a dynamic and editable website for NLE’s Rotary School, Hubballi, with the platform structured around the school’s CBSE-oriented requirements. The application was developed using React and Vite on the frontend and Node.js for backend functionality. Unlike a static website, the platform was designed with dynamic content management capabilities so that relevant information could be updated without modifying the entire application. PostgreSQL was used for database storage, with Supabase integrated for database management and backend connectivity. The project focused on creating a professional, responsive, maintainable, and content-editable school website while providing practical experience in full-stack development, database integration, and deployment-oriented web engineering.", details: "React · Vite · Node.js · PostgreSQL" },
  { name: "Smart Medical Kit", type: "Industry project · HAEGL Technologies", year: "2026", category: "HEALTH / IOT", image: image14, description: "The Smart Medical Kit is an embedded IoT system developed to capture pressure distribution and wrist movement information for physical assessment and analysis. The system incorporates a 20×20 pressure sensor matrix capable of measuring the distribution of pressure across the sensing surface and determining the user’s Center of Pressure based on their interaction with the mat. A separate gyroscopic mouse device was developed to capture wrist movements and provide information about the user’s motion patterns. The combined system allows pressure and motion data to be visualized so that doctors can analyze areas of weakness or abnormal movement and use the collected information as an additional input during assessment and treatment planning. The project combined embedded systems, sensor interfacing, IoT, motion sensing, pressure mapping, and data visualization.", details: "Embedded systems · Sensors · Data visualization" },
  { name: "STARK-VISION", type: "Personal project", year: "2026", category: "PRIVACY / VISION", image: image15, description: "STARK-VISION is a privacy-first Progressive Web Application developed to demonstrate real-time facial recognition and computer vision directly within a web browser. Unlike conventional cloud-based facial recognition systems, the application is designed around a local-first architecture where the major stages of the computer vision pipeline are executed on the user’s device. The application uses Next.js, TypeScript, Tailwind CSS, shadcn/ui, Prisma ORM, and SQLite, with face-api.js and the SSD MobileNet v1 model providing real-time face detection. Each detected face is converted into a 128-dimensional facial descriptor, which is compared using Euclidean distance for identity recognition. The application also supports multiple-face detection and recognition, real-time age and gender estimation, and confidence information for predictions. Performance was optimized through techniques such as requestAnimationFrame-based processing, image resizing, createImageBitmap, and efficient frame handling. The local-first architecture is intended to prevent facial images and biometric information from being transmitted to external servers while supporting offline operation and local storage of face descriptors.", details: "Next.js · TypeScript · face-api.js · SQLite" },
  { name: "Vision-Based Robot Simulator", type: "Personal project", year: "2026", category: "ROBOTICS / 3D", image: image16, description: "The Vision-Based Robot Simulator is a web-based robotics platform developed to study the integration of Computer Vision, Artificial Intelligence, and Human-Robot Interaction across multiple robotic systems. The platform simulates approximately 20 different robotic systems representing industrial and service applications such as collaborative robotic arms, pick-and-place robots, welding robots, inspection robots, medical robots, agricultural robots, warehouse robots, surveillance robots, and autonomous service robots. The system uses MediaPipe Pose and Hand Landmarker models to perform real-time markerless human pose estimation and hand tracking through a standard webcam. The extracted landmarks are processed using geometric feature extraction, vector mathematics, joint-angle estimation, palm-orientation analysis, coordinate transformations, and temporal filtering. These measurements are then mapped to a 6-DOF robotic arm within a real-time 3D simulation environment. The application was developed using React, TypeScript, Vite, Three.js, React Three Fiber, and Tailwind CSS, with a modular architecture separating vision processing, motion filtering, robot kinematics, and visualization.", details: "React · Three.js · React Three Fiber · MediaPipe" },
  { name: "HAEGL PARAKRAMA Deployment", type: "HAEGL Technologies", year: "2026", category: "DEPLOYMENT", image: image17, description: "This project involved the production deployment of the HAEGL PARAKRAMA website using cPanel hosting infrastructure. The deployment process included configuring the hosting environment, transferring the production website, setting up the required hosting configuration, and validating the deployed application to ensure that the website was accessible through its production environment. The work provided practical experience with web hosting, cPanel-based deployment, production configuration, and website delivery.", details: "cPanel · Production hosting" },
  { name: "Terra CRM Testing", type: "HAEGL Technologies", year: "2026", category: "QUALITY ASSURANCE", image: image18, description: "Worked as a Testing Engineer for Terra CRM, contributing to the functional validation and quality assurance of the CRM software. The work involved testing application workflows, validating individual features, identifying software defects, checking application behaviour against expected functionality, and validating corrections after issues were addressed. This provided practical experience in software quality assurance, functional testing, defect identification, regression testing, and validation of real-world business software.", details: "Functional testing · Regression testing" },
  { name: "Multi-Application Deployment", type: "HAEGL Technologies", year: "2026", category: "DEPLOYMENT", image: image19, description: "Worked on the deployment of multiple HAEGL Technologies web applications into production environments using cPanel. The applications included InQuote, EduForge, the Hybrid Solar Dryer Dashboard, and the Smart Medical Kit web application. The deployment work involved configuring the hosting environment, publishing the applications, validating production accessibility, and ensuring that the deployed web applications were available for client use and demonstration. This work provided practical experience in production deployment of full-stack applications and managing multiple web projects within a shared hosting environment.", details: "cPanel · Full-stack deployment" },
];
